const provinsiBahasa = [
  { provinsi: "Aceh", bahasa: "Bahasa Aceh" },
  { provinsi: "Sumatera Utara", bahasa: "Bahasa Batak Toba" },
  { provinsi: "Sumatera Barat", bahasa: "Bahasa Minangkabau" },
  { provinsi: "Riau", bahasa: "Bahasa Melayu Riau" },
  { provinsi: "Kepulauan Riau", bahasa: "Bahasa Melayu" },
  { provinsi: "Jambi", bahasa: "Bahasa Jambi" },
  { provinsi: "Sumatera Selatan", bahasa: "Bahasa Palembang" },
  { provinsi: "Bangka Belitung", bahasa: "Bahasa Melayu Bangka" },
  { provinsi: "Bengkulu", bahasa: "Bahasa Rejang" },
  { provinsi: "Lampung", bahasa: "Bahasa Lampung" },
  { provinsi: "DKI Jakarta", bahasa: "Bahasa Betawi" },
  { provinsi: "Jawa Barat", bahasa: "Bahasa Sunda" },
  { provinsi: "Banten", bahasa: "Bahasa Banten" },
  { provinsi: "Jawa Tengah", bahasa: "Bahasa Jawa" },
  { provinsi: "DI Yogyakarta", bahasa: "Bahasa Jawa" },
  { provinsi: "Jawa Timur", bahasa: "Bahasa Jawa" },
  { provinsi: "Bali", bahasa: "Bahasa Bali" },
  { provinsi: "NTB", bahasa: "Bahasa Sasak" },
  { provinsi: "NTT", bahasa: "Bahasa Sumba" },
  { provinsi: "Kalimantan Barat", bahasa: "Bahasa Dayak" },
  { provinsi: "Kalimantan Tengah", bahasa: "Bahasa Ngaju" },
  { provinsi: "Kalimantan Selatan", bahasa: "Bahasa Banjar" },
  { provinsi: "Kalimantan Timur", bahasa: "Bahasa Kutai" },
  { provinsi: "Kalimantan Utara", bahasa: "Bahasa Tidung" },
  { provinsi: "Sulawesi Utara", bahasa: "Bahasa Manado" },
  { provinsi: "Sulawesi Tengah", bahasa: "Bahasa Kaili" },
  { provinsi: "Sulawesi Selatan", bahasa: "Bahasa Bugis" },
  { provinsi: "Sulawesi Tenggara", bahasa: "Bahasa Tolaki" },
  { provinsi: "Gorontalo", bahasa: "Bahasa Gorontalo" },
  { provinsi: "Sulawesi Barat", bahasa: "Bahasa Mandar" },
  { provinsi: "Maluku", bahasa: "Bahasa Ambon" },
  { provinsi: "Maluku Utara", bahasa: "Bahasa Ternate" },
  { provinsi: "Papua", bahasa: "Bahasa Papua" },
  { provinsi: "Papua Barat", bahasa: "Bahasa Biak" },
  { provinsi: "Papua Tengah", bahasa: "Bahasa Mee" },
  { provinsi: "Papua Pegunungan", bahasa: "Bahasa Lani" },
  { provinsi: "Papua Selatan", bahasa: "Bahasa Marind" },
  { provinsi: "Papua Barat Daya", bahasa: "Bahasa Moi" },
];